// Command genfreq derives a Japanese word-frequency list from a Tatoeba
// Japanese sentences export and writes it as the committed content/ja/frequency.tsv.
//
// It is an OFFLINE build-time tool, intentionally kept in its own Go module so
// that its tokenizer dependency (kagome, pure Go, MIT; bundling MeCab IPADIC,
// a BSD-style dictionary) never enters the shipped binary's module graph. The
// repository ships only the derived list — not kagome and not the raw corpus.
//
// Input: a Tatoeba per-language export (id<TAB>lang<TAB>text), e.g.
// https://downloads.tatoeba.org/exports/per_language/jpn/jpn_sentences.tsv.bz2
// (CC BY 2.0 FR — attribution recorded in NOTICE; see
// docs/adr/0001-japanese-frequency-list.md).
//
// Usage:
//
//	go run . -in jpn_sentences.tsv -out ../../content/ja/frequency.tsv -n 10000
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/ikawaha/kagome-dict/ipa"
	"github.com/ikawaha/kagome/v2/tokenizer"
)

// IPADIC feature column indexes (mecab-ipadic).
const (
	posIndex      = 0 // 品詞 (part of speech)
	baseFormIndex = 6 // 基本形 (dictionary/base form)
	readingIndex  = 7 // 読み (reading, in katakana)
)

type word struct {
	surface string
	reading string
	count   int
}

func main() {
	in := flag.String("in", "", "path to a Tatoeba jpn_sentences.tsv export (id<TAB>lang<TAB>text)")
	out := flag.String("out", "../../content/ja/frequency.tsv", "output frequency list path")
	topN := flag.Int("n", 10000, "keep the N most frequent words")
	flag.Parse()

	if *in == "" {
		fmt.Fprintln(os.Stderr, "genfreq: -in is required")
		os.Exit(2)
	}
	if err := run(*in, *out, *topN); err != nil {
		fmt.Fprintf(os.Stderr, "genfreq: %v\n", err)
		os.Exit(1)
	}
}

func run(in, out string, topN int) error {
	t, err := tokenizer.New(ipa.Dict(), tokenizer.OmitBosEos())
	if err != nil {
		return fmt.Errorf("new tokenizer: %w", err)
	}

	f, err := os.Open(in)
	if err != nil {
		return fmt.Errorf("open input: %w", err)
	}
	defer f.Close()

	counts := make(map[string]*word)
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 0, 64*1024), 4*1024*1024)
	for sc.Scan() {
		fields := strings.Split(sc.Text(), "\t")
		if len(fields) < 3 {
			continue
		}
		for _, tok := range t.Tokenize(fields[2]) {
			if tok.Class == tokenizer.DUMMY {
				continue
			}
			feat := tok.Features()
			if len(feat) <= posIndex || strings.HasPrefix(feat[posIndex], "記号") {
				continue
			}
			surface := tok.Surface
			if len(feat) > baseFormIndex && feat[baseFormIndex] != "*" {
				surface = feat[baseFormIndex]
			}
			if !hasJapanese(surface) {
				continue
			}
			reading := ""
			if len(feat) > readingIndex && feat[readingIndex] != "*" {
				reading = katakanaToHiragana(feat[readingIndex])
			} else if isAllKana(surface) {
				// IPADIC has no reading for some tokens; a kana surface is its
				// own reading (katakana normalized to hiragana).
				reading = katakanaToHiragana(surface)
			}
			w, ok := counts[surface]
			if !ok {
				w = &word{surface: surface, reading: reading}
				counts[surface] = w
			}
			if w.reading == "" {
				w.reading = reading
			}
			w.count++
		}
	}
	if err := sc.Err(); err != nil {
		return fmt.Errorf("read input: %w", err)
	}

	words := make([]*word, 0, len(counts))
	for _, w := range counts {
		words = append(words, w)
	}
	// Most frequent first; break ties by surface for deterministic output.
	sort.Slice(words, func(i, j int) bool {
		if words[i].count != words[j].count {
			return words[i].count > words[j].count
		}
		return words[i].surface < words[j].surface
	})
	if len(words) > topN {
		words = words[:topN]
	}

	var b strings.Builder
	b.WriteString("# Japanese word-frequency list derived from the Tatoeba Project corpus.\n")
	b.WriteString("# License: CC BY 2.0 FR — see NOTICE and docs/adr/0001-japanese-frequency-list.md.\n")
	b.WriteString("# Generated by tools/genfreq; do not edit by hand.\n")
	b.WriteString("# rank\tword\treading\tcount\n")
	for i, w := range words {
		fmt.Fprintf(&b, "%d\t%s\t%s\t%d\n", i+1, w.surface, w.reading, w.count)
	}
	if err := os.WriteFile(out, []byte(b.String()), 0o644); err != nil {
		return fmt.Errorf("write output: %w", err)
	}
	fmt.Printf("genfreq: wrote %d words to %s\n", len(words), out)
	return nil
}

// hasJapanese reports whether s contains at least one hiragana, katakana, or
// kanji *letter*. The ranges deliberately exclude the prolonged-sound mark (ー)
// and middle dot (・), whose Unicode script is "Common", so standalone marks are
// not counted as words.
func hasJapanese(s string) bool {
	for _, r := range s {
		switch {
		case r >= 0x3041 && r <= 0x3096, // hiragana letters
			r >= 0x30A1 && r <= 0x30FA, // katakana letters
			r >= 0x4E00 && r <= 0x9FFF: // CJK unified ideographs
			return true
		}
	}
	return false
}

// isAllKana reports whether every rune in s is hiragana or katakana (including
// the prolonged-sound mark ー).
func isAllKana(s string) bool {
	if s == "" {
		return false
	}
	for _, r := range s {
		switch {
		case r >= 0x3040 && r <= 0x309F, // hiragana
			r >= 0x30A0 && r <= 0x30FF: // katakana (incl. ー)
		default:
			return false
		}
	}
	return true
}

// katakanaToHiragana maps full-width katakana to hiragana so readings are shown
// in the same script learners decode first.
func katakanaToHiragana(s string) string {
	return strings.Map(func(r rune) rune {
		if r >= 0x30A1 && r <= 0x30F6 {
			return r - 0x60
		}
		return r
	}, s)
}
