// Command genglobe renders the rotating braille globe frames embedded in the
// main menu header and writes them as the internal/art/globe.go source.
//
// It is a build-time tool, not part of the shipped binary. It fetches
// public-domain Natural Earth coastlines, projects them orthographically onto a
// braille canvas (land filled, faint disc outline), and emits one frame per step
// of a full rotation, with frame 0 facing Japan.
//
// Usage:
//
//	go run ./tools/genglobe -o internal/art/globe.go
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"math"
	"net/http"
	"os"
	"strings"
	"time"
)

// landURL is the public-domain Natural Earth 1:110m land polygons.
const landURL = "https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_land.geojson"

// Globe rendering parameters. N is the canvas size in braille dots (square);
// the center faces Japan; frames step the longitude through a full turn.
const (
	dots   = 32
	lon0   = 138.0
	lat0   = 37.0
	frames = 36
)

type point [2]float64 // lon, lat

// a polygon is a list of rings (outer + holes); each ring is a list of points.
var polygons [][][]point

func main() {
	out := flag.String("o", "", "output file (default stdout)")
	flag.Parse()

	if err := loadLand(); err != nil {
		die(err)
	}

	var buf bytes.Buffer
	writeSource(&buf)

	if *out == "" {
		if _, err := os.Stdout.Write(buf.Bytes()); err != nil {
			die(err)
		}
		return
	}
	if err := os.WriteFile(*out, buf.Bytes(), 0o644); err != nil {
		die(err)
	}
}

func die(err error) {
	_, _ = fmt.Fprintln(os.Stderr, "genglobe:", err)
	os.Exit(1)
}

func loadLand() error {
	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Get(landURL)
	if err != nil {
		return fmt.Errorf("fetch land data: %w", err)
	}
	defer func() { _ = resp.Body.Close() }()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("fetch land data: %s", resp.Status)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return fmt.Errorf("read land data: %w", err)
	}

	var fc struct {
		Features []struct {
			Geometry struct {
				Type        string          `json:"type"`
				Coordinates json.RawMessage `json:"coordinates"`
			} `json:"geometry"`
		} `json:"features"`
	}
	if err := json.Unmarshal(body, &fc); err != nil {
		return fmt.Errorf("parse land data: %w", err)
	}
	for _, f := range fc.Features {
		switch f.Geometry.Type {
		case "Polygon":
			var poly [][]point
			if err := json.Unmarshal(f.Geometry.Coordinates, &poly); err != nil {
				return err
			}
			polygons = append(polygons, poly)
		case "MultiPolygon":
			var multi [][][]point
			if err := json.Unmarshal(f.Geometry.Coordinates, &multi); err != nil {
				return err
			}
			polygons = append(polygons, multi...)
		}
	}
	return nil
}

func writeSource(w io.Writer) {
	_, _ = fmt.Fprint(w, `// Code generated by tools/genglobe; DO NOT EDIT.
//
// Source data: Natural Earth ne_110m_land (public domain).
// Rendering: orthographic projection rasterized to a braille canvas, land
// filled, with a faint disc outline. 32 dots (16x8 cells), centered on Japan
// (lon 138, lat 37). 36 frames at 10-degree steps; frame 0 is the resting
// frame facing Japan, and the sequence rotates a full turn back to it.
//
// Regenerate with: go generate ./internal/art

package art

// GlobeFrames holds the braille frames of the rotating Earth shown in the main
// menu header. Frame 0 faces Japan (the target language); successive frames
// spin the globe a full turn and return to frame 0.
var GlobeFrames = []string{
`)
	for i := 0; i < frames; i++ {
		lon := lon0 + float64(i)*360.0/frames
		grid := strings.TrimRight(render(dots, lon, lat0), "\n")
		_, _ = fmt.Fprintf(w, "\t`%s`,\n", grid)
	}
	_, _ = fmt.Fprint(w, "}\n")
}

// braille dot bit per (x in 0..1, y in 0..3).
var dotbit = [4][2]byte{
	{0x01, 0x08},
	{0x02, 0x10},
	{0x04, 0x20},
	{0x40, 0x80},
}

func deg2rad(d float64) float64 { return d * math.Pi / 180 }

// render draws an orthographic globe of N x N dots centered on lon0c/lat0c
// (degrees) and packs it into braille runes. Land is filled; a faint circle
// marks the disc edge so the sphere reads even over ocean.
func render(N int, lon0c, lat0c float64) string {
	lam0 := deg2rad(lon0c)
	phi0 := deg2rad(lat0c)
	land := make([][]bool, N)
	for y := 0; y < N; y++ {
		land[y] = make([]bool, N)
		for x := 0; x < N; x++ {
			nx := (float64(x)+0.5)/float64(N)*2 - 1
			ny := 1 - (float64(y)+0.5)/float64(N)*2
			rho := math.Hypot(nx, ny)
			if rho > 1 {
				continue
			}
			if rho > 0.965 {
				land[y][x] = true // disc outline
				continue
			}
			c := math.Asin(rho)
			sinc, cosc := math.Sin(c), math.Cos(c)
			var lat, lon float64
			if rho < 1e-9 {
				lat, lon = phi0, lam0
			} else {
				lat = math.Asin(cosc*math.Sin(phi0) + ny*sinc*math.Cos(phi0)/rho)
				lon = lam0 + math.Atan2(nx*sinc, rho*cosc*math.Cos(phi0)-ny*sinc*math.Sin(phi0))
			}
			latd := lat * 180 / math.Pi
			lond := lon * 180 / math.Pi
			for lond > 180 {
				lond -= 360
			}
			for lond < -180 {
				lond += 360
			}
			if isLand(lond, latd) {
				land[y][x] = true
			}
		}
	}

	cols, rows := N/2, N/4
	var sb strings.Builder
	for cy := 0; cy < rows; cy++ {
		for cx := 0; cx < cols; cx++ {
			var bits byte
			for dy := 0; dy < 4; dy++ {
				for dx := 0; dx < 2; dx++ {
					if land[cy*4+dy][cx*2+dx] {
						bits |= dotbit[dy][dx]
					}
				}
			}
			sb.WriteRune(rune(0x2800 + int(bits)))
		}
		sb.WriteByte('\n')
	}
	return sb.String()
}

func isLand(lon, lat float64) bool {
	for _, poly := range polygons {
		cnt := 0
		for _, ring := range poly {
			if pointInRing(lon, lat, ring) {
				cnt++
			}
		}
		if cnt%2 == 1 {
			return true
		}
	}
	return false
}

func pointInRing(lon, lat float64, ring []point) bool {
	in := false
	j := len(ring) - 1
	for i := range ring {
		xi, yi := ring[i][0], ring[i][1]
		xj, yj := ring[j][0], ring[j][1]
		if (yi > lat) != (yj > lat) {
			if lon < (xj-xi)*(lat-yi)/(yj-yi)+xi {
				in = !in
			}
		}
		j = i
	}
	return in
}
